shopciti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shopciti_app.urls')),  # Include your app's URL patterns
    path('admin/', admin.site.urls),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopciti_app/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from . import views 
from .views import SupplierLoginView, UserLoginView, SupplierLogoutView, UserLogoutView


urlpatterns = [
    path('', views.home1, name='home_shops'),  # Define a home view
    path('home2/', views.home2, name='home2'),
    path('products/', views.product_list, name='product_list'),
    path('register/', views.register, name='register'),
    path('register-user/', views.register_user, name='register_user'),
    # Supplier login and logout
    path('login/', SupplierLoginView.as_view(), name='login'),
    path('logout/', SupplierLogoutView.as_view(), name='logout'),

#//////////////////////////////////////////////////////////////////
    path('index/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('become-vendor/', views.become_vendor, name='become_vendor'),
    path('blogs-details/', views.blogs_details, name='blogs_details'),
    path('blogs/', views.blogs, name='blogs'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('compaire/', views.compaire, name='compaire'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('create-account/', views.create_account, name='create_account'),
    path('empty-cart/', views.empty_cart, name='empty_cart'),
    path('empty-wishlist/', views.empty_wishlist, name='empty_wishlist'),
    path('faq/', views.faq, name='faq'),
    path('flash-sale/', views.flash_sale, name='flash_sale'),
    path('privacy/', views.privacy, name='privacy'),
    path('product-info/', views.product_info, name='product_info'),
    path('product-sidebar/', views.product_sidebar, name='product_sidebar'),
    path('seller-sidebar/', views.seller_sidebar, name='seller_sidebar'),
    path('sellers/', views.sellers, name='sellers'),
    path('terms/', views.terms, name='terms'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('wishlist/', views.wishlist, name='wishlist'),

    # User login and logout
    path('login-user/', UserLoginView.as_view(), name='login_user'),
    path('logout-user/', UserLogoutView.as_view(), name='logout_user'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('account-user-info/', views.account_user_info, name='account_user_info'),
    path('user-orders/', views.account_user_info, name='user_orders'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('register-store/', views.register_store, name='register_store'),
    path('registration-success/', views.registration_success, name='registration_success'),
    path('registration-failure/', views.registration_failure, name='registration_failure'),
    path('shops/', views.shop_list, name='shop_list'),
    path('shop/<int:shop_id>/', views.shop_detail, name='shop_detail'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('payfast-return/', views.payfast_return, name='payfast_return'),
    path('payfast-notify/', views.payfast_notify, name='payfast_notify'),
    path('order_confirmation/', views.order_confirmation, name='order_confirmation'),
    path('store-profile/', views.store_profile, name='store_profile'),
    path('store-profile-free/', views.store_profile_free, name='store_profile_free'),
    path('manage-products/<int:store_id>/', views.manage_products, name='manage_products'),
    path('store/<int:store_id>/add-product/', views.add_product_to_store, name='add_product_to_store'),
    path('product/<int:product_id>/edit/', views.edit_product, name='edit_product'),
    path('product/<int:product_id>/delete/', views.delete_product, name='delete_product'),
    path('thank_you/', views.thank_you, name='thank_you'),

]

shopciti_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model


class Store(models.Model):
    SUBSCRIPTION_CHOICES = [
        ("free", "Free"),
        ("basic", "Basic"),
        ("premium", "Premium"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    contact_email = models.EmailField(blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=10, blank=True, null=True)
    logo = models.ImageField(upload_to='store_logos/', default='static/img/1.png')
    about = models.TextField(blank=True, null=True)
    
    subscription_level = models.CharField(max_length=10, choices=SUBSCRIPTION_CHOICES, default="free")

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, blank=True)
    about = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='profile_image/', blank=True, null=True)

    class Meta:
        app_label = 'shopciti_app'


    # Add a related_name to avoid clashes
    groups = models.ManyToManyField(
        "auth.Group",
        blank=True,
        related_name="customuser_set",
        related_query_name="customuser",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        blank=True,
        related_name="customuser_set",
        related_query_name="customuser",
    )

class StoreProfile(models.Model):
    store = models.OneToOneField(Store, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to='store_logos/', blank=True, null=True)


    def __str__(self):
        return self.store.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')

    # Add a foreign key to the Store model to represent the relationship
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)  # Add this ForeignKey

    def __str__(self):
        return self.name

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)





class Review(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rating = models.IntegerField()  # You can use a rating field or create a separate model for ratings
    comment = models.TextField()

shopciti_app/views.py
from .models import Product
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Store  # Import the Store model if you have it
from django.contrib.auth.decorators import login_required
from .models import Store, StoreProfile
from .forms import CustomUserCreationForm
from django.core.exceptions import ObjectDoesNotExist
from .forms import UserProfileForm, StoreForm, CartAddProductForm, ProductForm, CheckoutForm
from django.core.paginator import Paginator
from django.db.models import Q
from .cart import Cart
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse



def about(request):
    return render(request, 'about.html')


def become_vendor(request):
    return render(request, 'become_vendor.html')


def blogs_details(request):
    return render(request, 'blogs_details.html')

def blogs(request):
    return render(request, 'blogs.html')

def cart(request):
    return render(request, 'cart.html')

def checkout(request):
    return render(request, 'checkout.html')

def compaire(request):
    return render(request, 'compaire.html')


def contact_us(request):
    return render(request, 'contact_us.html')

def create_account(request):
    return render(request, 'create_account.html')

def empty_cart(request):
    return render(request, 'empty_cart.html')

def empty_wishlist(request):
    return render(request, 'empty_wishlist.html')

def faq(request):
    return render(request, 'faq.html')

def flash_sale(request):
    return render(request, 'flash_sale.html')

def blogs_details(request):
    return render(request, 'blogs_details.html')

def flash(request):
    return render(request, 'flash.html')

def index(request):
    return render(request, 'index.html')

def login(request):
    return render(request, 'login.html')

def order(request):
    return render(request, 'order.html')

def privacy(request):
    return render(request, 'privacy.html')


def product_info(request):
    return render(request, 'product_info.html')


def product_sidebar(request):
    return render(request, 'product_sidebar.html')


def seller_sidebar(request):
    return render(request, 'seller_sidebar.html')

def sellers(request):
    return render(request, 'sellers.html')


def terms(request):
    return render(request, 'terms.html')

def user_profile(request):
    return render(request, 'user_profile.html')

def wishlist(request):
    return render(request, 'wishlist.html')

# /////////////////////////////////////////////////////////

class SupplierLoginView(LoginView):
    template_name = 'shopciti_app/login.html'

class UserLoginView(LoginView):
    template_name = 'shopciti_app/login_user.html'

    def get_success_url(self):
        # Get the 'next' parameter from the request
        next_url = self.request.GET.get('next')
        
        # Check if the 'next' parameter is a valid URL
        if next_url and self.request.build_absolute_uri(next_url) == next_url:
            return next_url
        else:
            # Redirect to a default URL if 'next' is not a valid URL
            return '/'

    def form_valid(self, form):
        # Call the parent class's form_valid method, which performs the login
        response = super().form_valid(form)

        # Redirect to the URL obtained from get_success_url
        return HttpResponseRedirect(self.get_success_url())

# You can also create similar custom views for logout if needed
class SupplierLogoutView(LogoutView):
    pass

class UserLogoutView(LogoutView):
    pass


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('register_store')  # Redirect to the user's profile page
    else:
        form = CustomUserCreationForm()
    return render(request, 'shopciti_app/register.html', {'form': form})

def register_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('account_user_info')  # Redirect to the user's profile page
    else:
        form = CustomUserCreationForm()
    return render(request, 'shopciti_app/register_user.html', {'form': form})


def product_list(request):
    products = Product.objects.all()
    return render(request, 'shopciti_app/product_list.html', {'products': products})

def home2(request):
    return render(request, 'shopciti_app/home2.html')

def home1(request):
    return render(request, 'shopciti_app/home1.html')

@login_required
def user_profile(request):
    user = request.user

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully.')

    else:
        form = UserProfileForm(instance=user)

    try:
        store = user.store
    except ObjectDoesNotExist:
        store = None

    try:
        store_profile = StoreProfile.objects.get(store=store)
    except ObjectDoesNotExist:
        store_profile = None

    profile_image_url = None
    if user.profile_image and user.profile_image.url:
        profile_image_url = user.profile_image.url

    return render(request, 'shopciti_app/store_profile.html', {
        'user': user,
        'store': store,
        'store_profile': store_profile,
        'profile_image_url': profile_image_url,
        'form': form,
    })

def account_user_info(request):
    return render(request, 'shopciti_app/account_user_info.html')

def user_orders(request):
    return render(request, 'shopciti_app/user_orders.html')


@login_required
def edit_profile(request):
    user = request.user
    store_name = None  # Default value for store_name

    # Check if the user has an associated store
    if hasattr(user, 'store'):
        store = user.store
        subscription_level = store.subscription_level
        store_name = store.name  # Assign store name if available

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            form.save()

            # Update store name if present in the form data
            if 'store_name' in request.POST:
                store_name = request.POST['store_name']
                if hasattr(user, 'store'):
                    user.store.name = store_name
                    user.store.save()

            messages.success(request, 'Your profile has been updated successfully.')
            return redirect('user_profile')

    else:
        form = UserProfileForm(instance=user)

    return render(request, 'shopciti_app/edit_profile.html', {'form': form, 'subscription_level': subscription_level, 'store_name': store_name})



@login_required
def register_store(request):
    user = request.user
    subscription_level = "free"
    
    if hasattr(user, 'profile'):
        subscription_level = user.profile.subscription_level

    if request.method == 'POST':
        form = StoreForm(request.POST, request.FILES)
        if form.is_valid():
            new_store = form.save()
            user.store = new_store
            user.save()

            if subscription_level == "free":
                return render(request, 'shopciti_app/store_profile_free.html')
            else:
                return render(request, 'shopciti_app/store_profile.html')

    else:
        form = StoreForm()

    return render(request, 'shopciti_app/register_store.html', {'form': form, 'subscription_level': subscription_level})


def registration_success(request):
    # Render the registration success or thank you page
    return render(request, 'registration_success.html')

def registration_failure(request):
    # Render a page indicating registration failure with appropriate message
    return render(request, 'shopciti_app/registration_failure.html')



def shop_list(request):
    search_query = request.GET.get('search_query', '')
    category = request.GET.get('category', '')
    sort_by = request.GET.get('sort_by', 'name')
    

    # Use Q objects to create complex queries for searching
    filter_criteria = Q(name__icontains=search_query)

    # Add more fields as needed to search in other attributes of the Store model
    if category:
        filter_criteria |= Q(category__icontains=category)

    if not sort_by:
        sort_by = 'name'  # Set a default sorting option if 'sort_by' is empty
    shops = Store.objects.filter(filter_criteria).order_by(sort_by)

    paginator = Paginator(shops, 10)
    page = request.GET.get('page')
    shops = paginator.get_page(page)

    context = {
        'shops': shops,
    }
    return render(request, 'shopciti_app/shop_list.html', context)


def shop_detail(request, shop_id):
    shop = get_object_or_404(Store, pk=shop_id)
    products = Product.objects.filter(store=shop)
    return render(request, 'shopciti_app/shop_detail.html', {'shop': shop, 'products': products})


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'shopciti_app/product_detail.html', {'product': product})

@login_required
def store_profile(request):
    user = request.user
    try:
        store = user.store
    except ObjectDoesNotExist:
        # Handle the case where the custom user or store does not exist
        return redirect('registration_failure')

    try:
        store_profile = StoreProfile.objects.get(store=store)
    except ObjectDoesNotExist:

shopciti_app/templates/shopciti_app/checkout.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <h1 class="text-center m-6" style="padding-top: 100px;">Checkout</h1>
    <div class="card" style="margin-top: 35px;">

        <div class="row">
            <div class="col-md-6 p-5">
                <h2>Items to purchase</h2>
                <ul class="list-group">
                    {% for item in cart_items %}
                    <li class="list-group-item">{{ item.name }} - Price: R{{ item.price }} x {{ item.quantity }}</li>
                    {% endfor %}
                </ul>

                <h3>Total : R{{ total_amount }}</h3>
            </div>

            <div class="col-md-6 p-5">
                <h2>Select Payment Option:</h2>
                <form id="payment-form">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <label class="form-check-label">
                            <input type="radio" id="credit_card" name="payment_option" value="credit_card" class="form-check-input"> Credit Card
                        </label>
                        </li>
                        <li class="list-group-item">
                            <label class="form-check-label">
                            <input type="radio" id="paypal" name="payment_option" value="paypal" class="form-check-input"> PayPal
                        </label>
                        </li>
                        <li class="list-group-item">
                            <label class="form-check-label">
                            <input type="radio" id="payfast" name="payment_option" value="payfast" class="form-check-input"> PayFast
                        </label>
                        </li>
                    </ul>
                    <button type="button" class="btn btn-primary btn-block mt-3" id="process-payment">Process Payment</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    const merchantId = '23353254';
    const merchantKey = 'r7cx2yvt9i7gf';
    const totalAmount = '{{ total_amount | escapejs }}';
    const itemName = '{{ item_name | escapejs }}';

    document.getElementById('process-payment').addEventListener('click', function() {
        const selectedPaymentOption = document.querySelector('input[name="payment_option"]:checked');

        if (selectedPaymentOption) {
            const paymentOption = selectedPaymentOption.value;

            // Handle payment processing based on the selected payment option
            if (paymentOption === 'credit_card') {
                // Implement credit card payment logic
            } else if (paymentOption === 'paypal') {
                // Implement PayPal payment logic
            } else if (paymentOption === 'payfast') {
                // Redirect the user to PayFast's payment page
                window.location.href = `https://www.payfast.co.za/eng/process?merchant_id=${merchantId}&merchant_key=${merchantKey}&amount=${totalAmount}&item_name=${itemName}`;
            }
        } else {
            alert('Please select a payment option.');
        }
    });
</script>
{% endblock %}

shopciti_app/templates/shopciti_app/product_list.html
{% extends "base.html" %} {% block title %}Welcome to ShopCiti{% endblock %} {% block header %}Welcome to ShopCiti{% endblock %} {% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Product Listing</title>
</head>

<body>
    <h1>Product Listing</h1>
    <ul>
        {% for product in products %}
        <li>{{ product.name }} - Price: ${{ product.price }}</li>
        {% endfor %}
    </ul>
</body>

</html>
{% endblock %}

shopciti_app/templates/shopciti_app/registration_failure.html
{% extends "base.html" %} {% block title %}Welcome to ShopCiti{% endblock %} {% block header %}Welcome to ShopCiti{% endblock %} {% block content %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Failure</title>
</head>

<body>
    <h1>Registration Failed</h1>
    <p>Sorry, there was an error during the registration process. Please try again later.</p>
</body>

</html>

{% endblock %}

shopciti_app/templates/shopciti_app/shop_detail.html
{% extends "base2.html" %} {% block title %} {{ shop.name }} Details {% endblock %} {% block header %} {{ shop.name }} Details {% endblock %} {% block content %} {% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f8f8;
        margin: 0;
        padding: 0;
    }
    
    h1 {
        background-color: #333;
        color: #fff;
        padding: 10px;
        text-align: center;
    }
    
    h2 {
        margin-top: 20px;
        font-size: 24px;
        color: #333;
    }
    
    p {
        color: #555;
    }
    
    .container {
        margin-top: 20px;
    }
    
    .store-logo {
        max-width: 100%;
        height: auto;
        display: block;
    }
    
    .filter-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
        background-color: #fff;
        padding: 15px;
        border: 1px solid #e4e4e4;
        border-radius: 8px;
    }
    
    .filter-container input[type="text"],
    .filter-container select {
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }
    
    .filter-container button {
        padding: 8px 16px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-weight: bold;
        text-transform: uppercase;
    }
    
    .filter-container button:hover {
        background-color: #0056b3;
    }
    /* Widget Styles */
    
    .widget {
        background-color: #fff;
        border: 1px solid #e4e4e4;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 20px;
    }
    
    .widget h2 {
        font-size: 20px;
        font-weight: bold;
        color: #333;
        margin-bottom: 15px;
    }
    
    .widget h3 {
        font-size: 18px;
        font-weight: bold;
        color: #333;
    }
    
    .widget ul {
        list-style: none;
        padding: 0;
    }
    
    .widget ul li {
        font-size: 16px;
        margin-bottom: 5px;
        color: #666;
    }
    
    .widget p {
        font-size: 16px;
        color: #666;
        margin-top: 5px;
    }
    
    .widget select {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }
    
    .widget button {
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-weight: bold;
        text-transform: uppercase;
    }
    
    .widget button:hover {
        background-color: #0056b3;
    }
    /* Shop item style */
    
    .shop-item {
        max-width: 160px;
        max-height: 80px;
        border: 1px solid #e4e4e4;
        border-radius: 8px;
        transition: transform 0.2s ease-in-out;
        margin-bottom: 20px;
    }
    
    .shop-item h5 {
        font-size: 20px;
        margin-top: 0;
        color: #333;
    }
    
    .shop-item p {
        font-size: 14px;
        color: #666;
    }
    
    .shop-link {
        color: #007bff;
        text-decoration: none;
        font-weight: bold;
    }
    /* Custom styles for product cards */
    
    .products-list .shop-item {
        max-width: 160px;
        max-height: 80px;
        margin: 0 auto;
    }
    
    .products-list .shop-item .card {
        max-width: 100%;
    }
    
    .products-list .shop-item .card-img-top {
        max-width: 100%;
        height: auto;
        display: block;
    }
    
    .products-list .shop-item .card-img-top {
        max-width: 100% !important;
        height: 140px !important;
        display: block;
    }
</style>

<h1>{{ shop.name }} Details</h1>

<div class="container shop-details">
    <h2 class="text-center mt-4">Shop Information</h2>
    <div class="row">
        <div class="col-md-3">
            <img src="{{ shop.logo.url }}" alt="{{ shop.name }} Logo" class="store-logo img-fluid rounded-circle">
        </div>
        <div class="col-md-9">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <h4>{{ shop.name }}</h4>
                </li>
                <li class="list-group-item">
                    <strong>Description:</strong> {{ shop.description }}
                </li>
                <li class="list-group-item">
                    <strong>Contact Email:</strong> {{ shop.contact_email }}
                </li>
                <li class="list-group-item">
                    <strong>Phone Number:</strong> {{ shop.phone_number }}
                </li>
                <li class="list-group-item">
                    <strong>Address:</strong> {{ shop.address }}
                </li>
                <li class="list-group-item">
                    <strong>City:</strong> {{ shop.city }}
                </li>
            </ul>
        </div>
    </div>
</div>

<div>
    <hr></hr>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="widget">
                <h2>Filter and Sort</h2>
                <form method="get" action="{% url 'shop_list' %}">
                    <div class="d-flex">
                        <input type="text" name="search_query" placeholder="Search shops" class="form-control mr-2">
                        <div class="btn"><button type="submit" class="btn btn-primary">
                            <i class="fas fa-search"></i>
                        </button>
                        </div>
                    </div>
                    <div class="filter-widget pt-3">
                        <select name="category">
                        <option value="">All Categories</option>
                        <option value="electronics">Electronics</option>
                        <option value="fashion">Fashion</option>
                        <option value="food">Food</option>
                    </select>
                    </div>
                    <div class="filter-widget pt-3">
                        <select name="sort_by">
                        <option value="">Sort by</option>
                        <option value="name">Name</option>
                        <option value="popularity">Popularity</option>
                        <option value="ratings">Ratings</option>
                    </select>
                    </div>
                    <div class="filter-widget pt-3">
                        <h3>PRICE RANGE</h3>
                        <input type="text" id="price-range" readonly style="border:0; color:#333; font-weight:bold;">
                        <input type="range" id="price-range-slider" min="0" max="100" value="0" step="1">
                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-9">
            <section id="product1" class="section-p1 pt-0">
                <div class="row">
                    <h2>Products</h2>
                    {% for product in store.product_set.all %}
                    <a href="{% url 'product_detail' product_id=product.id %}">
                        <div class="pro-container pt-0">
                            <div class="pro pt-0">
                                <img src="{{ product.image.url }}" alt="">
                                <div class="des">
                                    <span>adidas</span>
                                    <h5>{{ product.name }}</h5>
                                    <div class="star">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                    </div>
                                    <h4>R{{ product.price }}</h4>
                                </div>
                                <button type="submit" class="btn btn-primary p-0">
                                    <i class="fal fa-shopping-cart cart"></i>
                                </button>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                    <div class="col-md-4 mb-4">
                        <p></p>
                        {% for product in products %}
                        <a href="{% url 'product_detail' product_id=product.id %}">
                            <div class="pro-container pt-0">
                                <div class="pro pt-0">
                                    <img src="{{ product.image.url }}" alt="">
                                    <div class="des">
                                        <span>adidas</span>
                                        <h5>{{ product.name }}</h5>
                                        <div class="star">
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                        </div>
                                        <h4>R{{ product.price }}</h4>
                                    </div>
                                    <a href=""><i class="fal fa-shopping-cart cart"></i></a>
                                </div>
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



</body>

</html>
{% endblock %}